### ISSUE TITLE
Does it support define myvar = value?

### ISSUE THREAD

**Issue by mathieuruellan** [mk-fg/systemd-cgroup-nftables-policy-manager#1]
Can i have a `define variable = "value"` and then use it in a rule?

example:
```
define VPN_SLICE" = "user.slice/user-1000.slice/user@1000.service/app.slice/myservice.service"
# myservice.service ::  add rule inet filter FORWARD socket cgroupv2 level 4 "$VPN_SLICE" mark set 1

```

kind regards

**Comment by mk-fg** [comment]
Hi.

No, it shouldn't work with the current code.

Config "parser" there is just a couple trivial regexps matching comment-lines like `# something :: add rule ...` and their backslash-continuations (if any), and it runs over raw config file without any kind of nftables-specific processing.
https://github.com/mk-fg/systemd-cgroup-nftables-policy-manager/blob/18f9699/scnpm.ml#L119-L121

Not sure if it should be possible to provide define-lines to libnftables' nft_run_cmd_from_buffer, as it might only parse those in config files, but I think that'd probably be one way to haphazardly implement such feature (that'd only work for e.g. one-liner defines).

Can definitely see how it might be useful, but yeah, not implemented, unfortunately.
